-- Point of Sale — the PostgreSQL schema of the stand-alone stack.
--
-- GENERATED by `npm run sample` (db/write-sample.ts) from manifest.json, so a
-- compose install and an Adminium install create the same tables. Do not edit
-- by hand: change the manifest and regenerate. src/data/sample-drift.test.ts
-- fails when this file and the manifest disagree.

DROP TABLE IF EXISTS pos_messages CASCADE;
DROP TABLE IF EXISTS pos_settings CASCADE;
DROP TABLE IF EXISTS pos_booking_rules CASCADE;
DROP TABLE IF EXISTS pos_gift_card_ledger CASCADE;
DROP TABLE IF EXISTS pos_loyalty_ledger CASCADE;
DROP TABLE IF EXISTS pos_refund_items CASCADE;
DROP TABLE IF EXISTS pos_refunds CASCADE;
DROP TABLE IF EXISTS pos_payments CASCADE;
DROP TABLE IF EXISTS pos_ticket_item_modifiers CASCADE;
DROP TABLE IF EXISTS pos_ticket_items CASCADE;
DROP TABLE IF EXISTS pos_gift_cards CASCADE;
DROP TABLE IF EXISTS pos_rewards CASCADE;
DROP TABLE IF EXISTS pos_tickets CASCADE;
DROP TABLE IF EXISTS pos_customers CASCADE;
DROP TABLE IF EXISTS pos_reservations CASCADE;
DROP TABLE IF EXISTS pos_shifts CASCADE;
DROP TABLE IF EXISTS pos_time_clock CASCADE;
DROP TABLE IF EXISTS pos_staff CASCADE;
DROP TABLE IF EXISTS pos_restaurant_tables CASCADE;
DROP TABLE IF EXISTS pos_modifiers CASCADE;
DROP TABLE IF EXISTS pos_modifier_groups CASCADE;
DROP TABLE IF EXISTS pos_menu_items CASCADE;
DROP TABLE IF EXISTS pos_menu_categories CASCADE;

CREATE TABLE pos_menu_categories (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(48),
  name VARCHAR(80) NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  icon VARCHAR(40),
  tint VARCHAR(32)
);

CREATE TABLE pos_menu_items (
  id SERIAL PRIMARY KEY,
  category_id INTEGER REFERENCES pos_menu_categories (id),
  slug VARCHAR(64),
  name VARCHAR(80) NOT NULL,
  short_name VARCHAR(24),
  description VARCHAR(280),
  price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  image TEXT,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  tags VARCHAR(120),
  position INTEGER NOT NULL DEFAULT 0,
  barcode VARCHAR(64)
);

CREATE TABLE pos_modifier_groups (
  id SERIAL PRIMARY KEY,
  item_id INTEGER NOT NULL REFERENCES pos_menu_items (id),
  slug VARCHAR(48),
  name VARCHAR(80) NOT NULL,
  kind TEXT NOT NULL DEFAULT 'radio' CHECK (kind IN ('radio', 'check')),
  min INTEGER NOT NULL DEFAULT 0,
  max INTEGER NOT NULL DEFAULT 1,
  hint VARCHAR(120),
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE pos_modifiers (
  id SERIAL PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES pos_modifier_groups (id),
  slug VARCHAR(48),
  name VARCHAR(80) NOT NULL,
  price_delta NUMERIC(12, 2) NOT NULL DEFAULT 0,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE pos_restaurant_tables (
  id SERIAL PRIMARY KEY,
  label VARCHAR(16) NOT NULL,
  seats INTEGER NOT NULL DEFAULT 2,
  zone VARCHAR(40),
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE pos_staff (
  id SERIAL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  initials VARCHAR(4),
  role VARCHAR(40),
  email VARCHAR(254),
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pos_time_clock (
  id SERIAL PRIMARY KEY,
  staff_id INTEGER NOT NULL REFERENCES pos_staff (id),
  clock_in TIMESTAMPTZ NOT NULL DEFAULT now(),
  clock_out TIMESTAMPTZ
);

CREATE TABLE pos_shifts (
  id SERIAL PRIMARY KEY,
  opened_by INTEGER REFERENCES pos_staff (id),
  staff VARCHAR(80),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  opening_float NUMERIC(12, 2) NOT NULL DEFAULT 0,
  counted_cash NUMERIC(12, 2),
  expected_cash NUMERIC(12, 2),
  over_short NUMERIC(12, 2),
  closed_by INTEGER REFERENCES pos_staff (id)
);

CREATE TABLE pos_reservations (
  id SERIAL PRIMARY KEY,
  code VARCHAR(12) UNIQUE,
  name VARCHAR(80) NOT NULL,
  mobile VARCHAR(32),
  email VARCHAR(254),
  party_size INTEGER NOT NULL DEFAULT 2,
  starts_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'seated', 'no_show', 'cancelled')),
  channel TEXT NOT NULL DEFAULT 'phone' CHECK (channel IN ('online', 'phone', 'walk_in')),
  table_id INTEGER REFERENCES pos_restaurant_tables (id),
  occasion VARCHAR(40),
  guest_request VARCHAR(280),
  staff_note VARCHAR(280),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  seated_at TIMESTAMPTZ
);

CREATE TABLE pos_customers (
  id SERIAL PRIMARY KEY,
  member_no VARCHAR(16) UNIQUE,
  name VARCHAR(80) NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  email VARCHAR(254),
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  points INTEGER NOT NULL DEFAULT 0,
  lifetime_points INTEGER NOT NULL DEFAULT 0,
  visits INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE pos_tickets (
  id SERIAL PRIMARY KEY,
  number VARCHAR(16) UNIQUE,
  table_id INTEGER REFERENCES pos_restaurant_tables (id),
  staff_id INTEGER REFERENCES pos_staff (id),
  shift_id INTEGER REFERENCES pos_shifts (id),
  guests INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'sent', 'paid', 'void')),
  kitchen_status TEXT NOT NULL DEFAULT 'new' CHECK (kitchen_status IN ('new', 'cooking', 'ready', 'served')),
  held BOOLEAN NOT NULL DEFAULT FALSE,
  merged_into_id INTEGER REFERENCES pos_tickets (id),
  discount_kind TEXT CHECK (discount_kind IN ('percent', 'amount', 'comp')),
  discount_value NUMERIC(12, 2),
  discount_reason VARCHAR(120),
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tax NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tip NUMERIC(12, 2) NOT NULL DEFAULT 0,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  charged NUMERIC(12, 2),
  reservation_id INTEGER REFERENCES pos_reservations (id),
  customer_id INTEGER REFERENCES pos_customers (id),
  channel TEXT CHECK (channel IN ('till', 'phone', 'web', 'app')),
  pickup_code VARCHAR(16),
  pickup_stage TEXT CHECK (pickup_stage IN ('queued', 'making', 'ready', 'collected')),
  ready_at TIMESTAMPTZ,
  notified_at TIMESTAMPTZ,
  signed_at TIMESTAMPTZ,
  receipt_via TEXT CHECK (receipt_via IN ('email', 'text', 'print', 'none')),
  receipt_to VARCHAR(254),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ
);

CREATE TABLE pos_rewards (
  id SERIAL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  points INTEGER NOT NULL DEFAULT 100,
  menu_item_id INTEGER NOT NULL REFERENCES pos_menu_items (id),
  icon VARCHAR(40),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE pos_gift_cards (
  id SERIAL PRIMARY KEY,
  code VARCHAR(16) UNIQUE,
  status TEXT NOT NULL DEFAULT 'inactive' CHECK (status IN ('inactive', 'active', 'void')),
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  issued_at TIMESTAMPTZ
);

CREATE TABLE pos_ticket_items (
  id SERIAL PRIMARY KEY,
  ticket_id INTEGER NOT NULL REFERENCES pos_tickets (id),
  menu_item_id INTEGER REFERENCES pos_menu_items (id),
  name VARCHAR(80) NOT NULL DEFAULT '',
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  seat INTEGER NOT NULL DEFAULT 1,
  notes VARCHAR(280),
  sent_at TIMESTAMPTZ,
  voided_at TIMESTAMPTZ,
  void_reason VARCHAR(120),
  voided_by INTEGER REFERENCES pos_staff (id),
  reward_id INTEGER REFERENCES pos_rewards (id),
  gift_card_id INTEGER REFERENCES pos_gift_cards (id)
);

CREATE TABLE pos_ticket_item_modifiers (
  id SERIAL PRIMARY KEY,
  ticket_item_id INTEGER NOT NULL REFERENCES pos_ticket_items (id),
  modifier_id INTEGER REFERENCES pos_modifiers (id),
  price_delta NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE pos_payments (
  id UUID PRIMARY KEY,
  ticket_id INTEGER NOT NULL REFERENCES pos_tickets (id),
  method TEXT NOT NULL CHECK (method IN ('cash', 'card', 'qr', 'gift_card')),
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tip NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tendered NUMERIC(12, 2),
  change NUMERIC(12, 2),
  reference VARCHAR(64),
  paid_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  staff_id INTEGER REFERENCES pos_staff (id)
);

CREATE TABLE pos_refunds (
  id UUID PRIMARY KEY,
  ticket_id INTEGER NOT NULL REFERENCES pos_tickets (id),
  method TEXT NOT NULL CHECK (method IN ('cash', 'card', 'qr', 'gift_card')),
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tax NUMERIC(12, 2) NOT NULL DEFAULT 0,
  reason VARCHAR(120),
  staff_id INTEGER REFERENCES pos_staff (id),
  refunded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pos_refund_items (
  id UUID PRIMARY KEY,
  refund_id UUID NOT NULL REFERENCES pos_refunds (id),
  ticket_item_id INTEGER NOT NULL REFERENCES pos_ticket_items (id),
  qty INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE pos_loyalty_ledger (
  id UUID PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES pos_customers (id),
  kind TEXT NOT NULL DEFAULT 'earn' CHECK (kind IN ('earn', 'redeem', 'adjust')),
  points INTEGER NOT NULL DEFAULT 0,
  visit INTEGER NOT NULL DEFAULT 0,
  reward_id INTEGER REFERENCES pos_rewards (id),
  ticket_id INTEGER REFERENCES pos_tickets (id),
  note VARCHAR(200),
  staff_id INTEGER REFERENCES pos_staff (id),
  at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pos_gift_card_ledger (
  id UUID PRIMARY KEY,
  card_id INTEGER NOT NULL REFERENCES pos_gift_cards (id),
  kind TEXT NOT NULL DEFAULT 'reload' CHECK (kind IN ('issue', 'reload', 'redeem', 'refund', 'adjust')),
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ticket_id INTEGER REFERENCES pos_tickets (id),
  staff_id INTEGER REFERENCES pos_staff (id),
  at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pos_booking_rules (
  id SERIAL PRIMARY KEY,
  opens VARCHAR(5) NOT NULL DEFAULT '17:00',
  closes VARCHAR(5) NOT NULL DEFAULT '21:00',
  slot_minutes INTEGER NOT NULL DEFAULT 30,
  covers_per_slot INTEGER NOT NULL DEFAULT 12,
  days_ahead INTEGER NOT NULL DEFAULT 5,
  max_party INTEGER NOT NULL DEFAULT 8,
  hold_minutes INTEGER NOT NULL DEFAULT 15,
  cancel_hours INTEGER NOT NULL DEFAULT 2,
  occasions JSONB
);

CREATE TABLE pos_settings (
  id SERIAL PRIMARY KEY,
  venue_name VARCHAR(80),
  venue_mark VARCHAR(4),
  address VARCHAR(200),
  phone VARCHAR(32),
  tax_rate_bp INTEGER NOT NULL DEFAULT 825,
  tip_presets JSONB,
  receipt_footer VARCHAR(200)
);

CREATE TABLE pos_messages (
  id UUID PRIMARY KEY,
  kind TEXT NOT NULL DEFAULT 'receipt' CHECK (kind IN ('receipt')),
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sent', 'failed', 'skipped')),
  to_address VARCHAR(254),
  language VARCHAR(16),
  ticket_id INTEGER REFERENCES pos_tickets (id),
  customer_id INTEGER REFERENCES pos_customers (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  error TEXT
);

CREATE INDEX idx_menu_items_category_id ON pos_menu_items (category_id);
CREATE INDEX idx_modifier_groups_item_id ON pos_modifier_groups (item_id);
CREATE INDEX idx_modifiers_group_id ON pos_modifiers (group_id);
CREATE INDEX idx_time_clock_staff_id ON pos_time_clock (staff_id);
CREATE INDEX idx_shifts_opened_by ON pos_shifts (opened_by);
CREATE INDEX idx_shifts_closed_by ON pos_shifts (closed_by);
CREATE INDEX idx_reservations_table_id ON pos_reservations (table_id);
CREATE INDEX idx_tickets_table_id ON pos_tickets (table_id);
CREATE INDEX idx_tickets_staff_id ON pos_tickets (staff_id);
CREATE INDEX idx_tickets_shift_id ON pos_tickets (shift_id);
CREATE INDEX idx_tickets_merged_into_id ON pos_tickets (merged_into_id);
CREATE INDEX idx_tickets_reservation_id ON pos_tickets (reservation_id);
CREATE INDEX idx_tickets_customer_id ON pos_tickets (customer_id);
CREATE INDEX idx_rewards_menu_item_id ON pos_rewards (menu_item_id);
CREATE INDEX idx_ticket_items_ticket_id ON pos_ticket_items (ticket_id);
CREATE INDEX idx_ticket_items_menu_item_id ON pos_ticket_items (menu_item_id);
CREATE INDEX idx_ticket_items_voided_by ON pos_ticket_items (voided_by);
CREATE INDEX idx_ticket_items_reward_id ON pos_ticket_items (reward_id);
CREATE INDEX idx_ticket_items_gift_card_id ON pos_ticket_items (gift_card_id);
CREATE INDEX idx_ticket_item_modifiers_ticket_item_id ON pos_ticket_item_modifiers (ticket_item_id);
CREATE INDEX idx_ticket_item_modifiers_modifier_id ON pos_ticket_item_modifiers (modifier_id);
CREATE INDEX idx_payments_ticket_id ON pos_payments (ticket_id);
CREATE INDEX idx_payments_staff_id ON pos_payments (staff_id);
CREATE INDEX idx_refunds_ticket_id ON pos_refunds (ticket_id);
CREATE INDEX idx_refunds_staff_id ON pos_refunds (staff_id);
CREATE INDEX idx_refund_items_refund_id ON pos_refund_items (refund_id);
CREATE INDEX idx_refund_items_ticket_item_id ON pos_refund_items (ticket_item_id);
CREATE INDEX idx_loyalty_ledger_customer_id ON pos_loyalty_ledger (customer_id);
CREATE INDEX idx_loyalty_ledger_reward_id ON pos_loyalty_ledger (reward_id);
CREATE INDEX idx_loyalty_ledger_ticket_id ON pos_loyalty_ledger (ticket_id);
CREATE INDEX idx_loyalty_ledger_staff_id ON pos_loyalty_ledger (staff_id);
CREATE INDEX idx_gift_card_ledger_card_id ON pos_gift_card_ledger (card_id);
CREATE INDEX idx_gift_card_ledger_ticket_id ON pos_gift_card_ledger (ticket_id);
CREATE INDEX idx_gift_card_ledger_staff_id ON pos_gift_card_ledger (staff_id);
CREATE INDEX idx_messages_ticket_id ON pos_messages (ticket_id);
CREATE INDEX idx_messages_customer_id ON pos_messages (customer_id);
