// Maps the design comp's kebab-case lucide names (data-lucide="…") to
// lucide-react named components, so the rest of the port keeps the comp's icon
// names verbatim. stroke-width 2 matches the comp's lucide.createIcons config.

import type { CSSProperties } from 'react';
import {
  AlertTriangle,
  AppWindow,
  Armchair,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AtSign,
  Banknote,
  Bell,
  BellRing,
  CakeSlice,
  Calculator,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  CloudOff,
  Coffee,
  CookingPot,
  Cookie,
  CornerDownLeft,
  CreditCard,
  Croissant,
  CupSoda,
  Delete,
  Droplet,
  Egg,
  Eraser,
  Flame,
  Gift,
  GitMerge,
  GlassWater,
  Grid2x2,
  Grid3x3,
  Grip,
  HandCoins,
  Inbox,
  LayoutGrid,
  Lock,
  Mail,
  MessageSquare,
  MessageSquareText,
  Minus,
  Moon,
  Pause,
  Percent,
  Plus,
  PlusCircle,
  Printer,
  QrCode,
  Receipt,
  ReceiptText,
  RotateCcw,
  Rows3,
  Salad,
  Sandwich,
  ScanLine,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Soup,
  Star,
  Store,
  Tablet,
  Tag,
  Trash2,
  Unlock,
  Utensils,
  Wand2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

const REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'app-window': AppWindow,
  armchair: Armchair,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'at-sign': AtSign,
  banknote: Banknote,
  bell: Bell,
  'bell-ring': BellRing,
  'cake-slice': CakeSlice,
  calculator: Calculator,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  clock: Clock,
  cloud: Cloud,
  'cloud-off': CloudOff,
  coffee: Coffee,
  'cooking-pot': CookingPot,
  cookie: Cookie,
  'corner-down-left': CornerDownLeft,
  'credit-card': CreditCard,
  croissant: Croissant,
  'cup-soda': CupSoda,
  delete: Delete,
  droplet: Droplet,
  egg: Egg,
  eraser: Eraser,
  flame: Flame,
  gift: Gift,
  'git-merge': GitMerge,
  'glass-water': GlassWater,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  grip: Grip,
  'hand-coins': HandCoins,
  inbox: Inbox,
  'layout-grid': LayoutGrid,
  lock: Lock,
  mail: Mail,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  minus: Minus,
  moon: Moon,
  pause: Pause,
  percent: Percent,
  plus: Plus,
  'plus-circle': PlusCircle,
  printer: Printer,
  'qr-code': QrCode,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  'rows-3': Rows3,
  salad: Salad,
  sandwich: Sandwich,
  'scan-line': ScanLine,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  soup: Soup,
  star: Star,
  store: Store,
  tablet: Tablet,
  tag: Tag,
  'trash-2': Trash2,
  unlock: Unlock,
  utensils: Utensils,
  'wand-2': Wand2,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  'x-circle': XCircle,
};

export interface IconProps {
  name: string;
  size?: number | string;
  color?: string;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
}

export function Icon({ name, size = 18, color, className, style, strokeWidth = 2 }: IconProps) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp size={size} color={color} className={className} style={style} strokeWidth={strokeWidth} />;
}
