// Maps the design comp's kebab-case lucide names (data-lucide="…") to
// lucide-react named components, so the rest of the port keeps the comp's icon
// names verbatim. stroke-width 2 matches the comp's lucide.createIcons config.

import type { CSSProperties } from 'react';
import {
  AlertTriangle,
  AppWindow,
  Armchair,
  ArrowDownLeft,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  Ban,
  Banknote,
  Bell,
  BellRing,
  CakeSlice,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  ChartColumn,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  CloudOff,
  Coffee,
  Cookie,
  CookingPot,
  CornerDownLeft,
  CreditCard,
  Croissant,
  CupSoda,
  Delete,
  Droplet,
  Egg,
  Eraser,
  Flame,
  Footprints,
  Gift,
  GitMerge,
  GlassWater,
  Globe,
  Grid2x2,
  Grid3x3,
  Grip,
  HandCoins,
  HandPlatter,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  MessageSquareText,
  Minus,
  Monitor,
  Moon,
  PartyPopper,
  Pause,
  PenLine,
  Percent,
  Phone,
  PhoneCall,
  Play,
  Plus,
  PlusCircle,
  Printer,
  QrCode,
  Receipt,
  ReceiptText,
  RotateCcw,
  Rows3,
  Salad,
  Sandwich,
  ScanLine,
  Search,
  SearchX,
  Send,
  ShoppingBag,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Soup,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  TicketCheck,
  Trash2,
  Undo2,
  Unlock,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Utensils,
  Wand2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

export const REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'app-window': AppWindow,
  armchair: Armchair,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'at-sign': AtSign,
  award: Award,
  ban: Ban,
  banknote: Banknote,
  bell: Bell,
  'bell-ring': BellRing,
  'cake-slice': CakeSlice,
  calculator: Calculator,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'chart-column': ChartColumn,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  clock: Clock,
  cloud: Cloud,
  'cloud-off': CloudOff,
  coffee: Coffee,
  cookie: Cookie,
  'cooking-pot': CookingPot,
  'corner-down-left': CornerDownLeft,
  'credit-card': CreditCard,
  croissant: Croissant,
  'cup-soda': CupSoda,
  delete: Delete,
  droplet: Droplet,
  egg: Egg,
  eraser: Eraser,
  flame: Flame,
  footprints: Footprints,
  gift: Gift,
  'git-merge': GitMerge,
  'glass-water': GlassWater,
  globe: Globe,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  grip: Grip,
  'hand-coins': HandCoins,
  'hand-platter': HandPlatter,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  'layout-grid': LayoutGrid,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'mail-check': MailCheck,
  menu: Menu,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  'party-popper': PartyPopper,
  pause: Pause,
  'pen-line': PenLine,
  percent: Percent,
  phone: Phone,
  'phone-call': PhoneCall,
  play: Play,
  plus: Plus,
  'plus-circle': PlusCircle,
  printer: Printer,
  'qr-code': QrCode,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  'rows-3': Rows3,
  salad: Salad,
  sandwich: Sandwich,
  'scan-line': ScanLine,
  search: Search,
  'search-x': SearchX,
  send: Send,
  'shopping-bag': ShoppingBag,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  soup: Soup,
  star: Star,
  store: Store,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  'ticket-check': TicketCheck,
  'trash-2': Trash2,
  'undo-2': Undo2,
  unlock: Unlock,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  utensils: Utensils,
  'wand-2': Wand2,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  'x-circle': XCircle,
};

export interface IconProps {
  name: string;
  size?: number | string;
  color?: string;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
}

export function Icon({ name, size = 18, color, className, style, strokeWidth = 2 }: IconProps) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp size={size} color={color} className={className} style={style} strokeWidth={strokeWidth} />;
}
