/**
 * The stand-alone stack's SQL — `db/schema.sql` and `db/seed.sql` — written
 * from the two documents that already say it all: the manifest's tables and
 * the sample bundle. An Adminium install and a `docker compose up` therefore
 * create the same tables and, with sample data, the same rows; the drift
 * between seed.sql and demo.ts that nothing used to catch cannot come back.
 *
 * PostgreSQL only (the compose stack's database). Pure: text in, text out —
 * `db/write-sample.ts` writes the files, sample-drift.test.ts compares them.
 */
import type { SampleBundle, SampleRow } from './sample';

interface Column {
  ref: string;
  type: string;
  role?: string;
  nullable?: boolean;
  references?: string;
  enum?: string[];
  default?: string | number | boolean;
  maxLength?: number;
  rules?: { sequence?: unknown; code?: unknown };
}
interface Table {
  ref: string;
  columns: Column[];
}
export interface ManifestTables {
  key: string;
  requiredSchema: { tables: Table[] };
}

const PREFIX = 'pos_';
const real = (ref: string) => `${PREFIX}${ref}`;
const quote = (text: string) => `'${text.replace(/'/g, "''")}'`;

/** Parents before the tables that point at them. */
function creationOrder(tables: Table[]): Table[] {
  const byRef = new Map(tables.map((t) => [t.ref, t]));
  const done = new Set<string>();
  const out: Table[] = [];
  const visit = (table: Table, path: Set<string>) => {
    if (done.has(table.ref)) return;
    if (path.has(table.ref)) throw new Error(`the tables point at each other in a cycle through "${table.ref}"`);
    path.add(table.ref);
    for (const column of table.columns) {
      if (column.type !== 'fk' || column.references === undefined || column.references === table.ref) continue;
      visit(byRef.get(column.references)!, path);
    }
    path.delete(table.ref);
    done.add(table.ref);
    out.push(table);
  };
  for (const table of tables) visit(table, new Set());
  return out;
}

function keyType(tables: Table[], ref: string): string {
  const pk = tables.find((t) => t.ref === ref)?.columns.find((c) => c.role === 'pk');
  return pk?.type === 'uuid' ? 'UUID' : 'INTEGER';
}

function columnSql(tables: Table[], column: Column): string {
  if (column.role === 'pk') return `${column.ref} ${column.type === 'uuid' ? 'UUID' : 'SERIAL'} PRIMARY KEY`;
  let type: string;
  switch (column.type) {
    case 'text':
      type = column.maxLength === undefined ? 'TEXT' : `VARCHAR(${String(column.maxLength)})`;
      break;
    case 'int':
      type = 'INTEGER';
      break;
    case 'bigint':
      type = 'BIGINT';
      break;
    case 'money':
      type = 'NUMERIC(12, 2)';
      break;
    case 'bool':
      type = 'BOOLEAN';
      break;
    case 'enum':
      type = 'TEXT';
      break;
    case 'timestamptz':
      type = 'TIMESTAMPTZ';
      break;
    case 'json':
      type = 'JSONB';
      break;
    case 'uuid':
      type = 'UUID';
      break;
    case 'fk':
      type = keyType(tables, column.references!);
      break;
    default:
      throw new Error(`no SQL type for manifest type "${column.type}" (${column.ref})`);
  }
  const parts = [column.ref, type];
  if (column.nullable !== true) parts.push('NOT NULL');
  if (column.default !== undefined) {
    const value = column.default;
    parts.push(
      `DEFAULT ${value === 'now' && column.type === 'timestamptz' ? 'now()' : typeof value === 'string' ? quote(value) : typeof value === 'boolean' ? (value ? 'TRUE' : 'FALSE') : String(value)}`,
    );
  }
  if (column.type === 'enum') parts.push(`CHECK (${column.ref} IN (${(column.enum ?? []).map(quote).join(', ')}))`);
  if (column.type === 'fk') parts.push(`REFERENCES ${real(column.references!)} (id)`);
  // A number from a counter and a code a guest types are each unique.
  if (column.rules?.sequence !== undefined || column.rules?.code !== undefined) parts.push('UNIQUE');
  return parts.join(' ');
}

export function schemaSql(manifest: ManifestTables): string {
  const tables = creationOrder(manifest.requiredSchema.tables);
  const out: string[] = [
    '-- Point of Sale — the PostgreSQL schema of the stand-alone stack.',
    '--',
    '-- GENERATED by `npm run sample` (db/write-sample.ts) from manifest.json, so a',
    '-- compose install and an Adminium install create the same tables. Do not edit',
    '-- by hand: change the manifest and regenerate. src/data/sample-drift.test.ts',
    '-- fails when this file and the manifest disagree.',
    '',
    ...[...tables].reverse().map((t) => `DROP TABLE IF EXISTS ${real(t.ref)} CASCADE;`),
    '',
  ];
  for (const table of tables) {
    out.push(`CREATE TABLE ${real(table.ref)} (`);
    out.push(table.columns.map((column) => `  ${columnSql(manifest.requiredSchema.tables, column)}`).join(',\n'));
    out.push(');', '');
  }
  for (const table of tables) {
    for (const column of table.columns) {
      if (column.type !== 'fk') continue;
      out.push(`CREATE INDEX idx_${table.ref}_${column.ref} ON ${real(table.ref)} (${column.ref});`);
    }
  }
  return `${out.join('\n')}\n`;
}

// ── seed.sql ────────────────────────────────────────────────────────────────

/** `P3DT2H`, `PT40M`: days, hours, minutes and seconds — the parts this file writes. */
const DURATION = /^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/;

export function seedSql(bundle: SampleBundle, manifest: ManifestTables): string {
  const tables = new Map(manifest.requiredSchema.tables.map((t) => [t.ref, t]));
  const keys = new Map<string, string>();
  const counters = new Map<string, number>();
  const out: string[] = [
    '-- Point of Sale — the stand-alone stack\'s demo rows.',
    '--',
    '-- GENERATED by `npm run sample` (db/write-sample.ts) from the same bundle an',
    '-- operator adds from Adminium (seeds/pos.sample.json), so the two cannot',
    '-- drift. Times are relative to when this file is loaded; names are English.',
    '-- Do not edit by hand.',
    '',
    'BEGIN;',
    '',
  ];

  const literal = (value: unknown, column: Column | undefined): string => {
    if (value === null || value === undefined) return 'NULL';
    if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
    if (typeof value === 'number') return String(value);
    if (typeof value === 'string') return quote(value);
    if (Array.isArray(value)) return `${quote(JSON.stringify(value))}::jsonb`;
    const record = value as Record<string, unknown>;
    if (typeof record['@ref'] === 'string') {
      const key = keys.get(record['@ref']);
      if (key === undefined) throw new Error(`"${record['@ref']}" is referenced before it is written`);
      return key;
    }
    if (typeof record['@ago'] === 'string') {
      const match = DURATION.exec(record['@ago']);
      if (match === null) throw new Error(`"${record['@ago']}" is not a duration this file writes`);
      const seconds = Number(match[1] ?? 0) * 86400 + Number(match[2] ?? 0) * 3600 + Number(match[3] ?? 0) * 60 + Number(match[4] ?? 0);
      return `now() - interval '${String(seconds)} seconds'`;
    }
    if (typeof record['@day'] === 'number' && typeof record['@time'] === 'string') {
      return `(current_date + ${String(record['@day'])} + time '${record['@time']}')::timestamptz`;
    }
    if (typeof record['@t'] === 'object' && record['@t'] !== null) {
      return quote((record['@t'] as Record<string, string>)['en-US']!);
    }
    if (column?.type === 'json') return `${quote(JSON.stringify(value))}::jsonb`;
    throw new Error(`cannot write ${JSON.stringify(value)}`);
  };

  for (const { ref, rows } of bundle.tables) {
    const table = tables.get(ref);
    if (table === undefined) throw new Error(`"${ref}" is not a table of the manifest`);
    const pk = table.columns.find((c) => c.role === 'pk')!;
    const columns = table.columns.filter((c) => c.role !== 'pk' && rows.some((row) => c.ref in row));
    const tuples = rows.map((row: SampleRow) => {
      let key: string;
      if (pk.type === 'uuid') {
        key = quote(String(row['id']));
      } else {
        const next = (counters.get(ref) ?? 0) + 1;
        counters.set(ref, next);
        key = String(next);
      }
      const label = row['@label'];
      if (typeof label === 'string') keys.set(label, key);
      const values = [key, ...columns.map((c) => (c.ref in row ? literal(row[c.ref], c) : 'DEFAULT'))];
      return `  (${values.join(', ')})`;
    });
    out.push(`INSERT INTO ${real(ref)} (${[pk.ref, ...columns.map((c) => c.ref)].join(', ')}) VALUES`);
    out.push(`${tuples.join(',\n')};`, '');
  }
  // Serial keys were written by hand above: move each counter past them.
  out.push('DO $$', 'BEGIN');
  for (const [ref] of counters) {
    out.push(`  PERFORM setval(pg_get_serial_sequence('${real(ref)}', 'id'), (SELECT MAX(id) FROM ${real(ref)}));`);
  }
  out.push('END', '$$;', '', 'COMMIT;');
  return `${out.join('\n')}\n`;
}
